services:
  db:
    image: mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: main
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 30s
  app:
    image: ghcr.io/suohcnamid/67-quiz:41e6302
    environment:
      - DATABASE_URL=jdbc:mariadb://db:3306/main
      - DATABASE_USERNAME=user
      - DATABASE_PASSWORD=password
    ports:
      - "8080:8080"
    depends_on:
      - db