name: "Generate OpenAPI docs"

on:
  push:
    tags:
      - "v*"
    branches:
      - dev

jobs:
  generate:
    runs-on: ubuntu-latest

    permissions:
      contents: write
      packages: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0

      - name: Make gradlew executable
        shell: bash
        run: chmod +x backend/gradlew

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 25

      - name: Build jar
        working-directory: backend
        run: |
          ./gradlew generateOpenApiDocs --no-daemon
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
